### PR TITLE
fix: avoid overriding the prefix option

### LINKED ISSUE #223: Current implementation breaks when combined with AutoLoad
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

The module explicitly states that `prefix` should be `undefined`, however, it still spreads the whole `...props` which might include `prefix` because of autoload.

See the troublesome code:
```javascript
  await fastify.register(require('./lib/routes'), {
    prefix: opts.routePrefix || '/documentation',
    uiConfig: opts.uiConfig || {},
    initOAuth: opts.initOAuth || {},
    hooks: opts.uiHooks,
    theme: opts.theme || {},
    logo: logoContent,
    ...opts
  })
```

Proposed solution: Spread `...opts` first, then override with our custom options as those should take precedence.
```javascript
  await fastify.register(require('./lib/routes'), {
    ...opts,
    prefix: opts.routePrefix || '/documentation',
    uiConfig: opts.uiConfig || {},
    initOAuth: opts.initOAuth || {},
    hooks: opts.uiHooks,
    theme: opts.theme || {},
    logo: logoContent,
  })
```

### Motivation

It's a simple fix, it's the expected behavior and... I spent around 2 hours debugging this source code because it was saying `GET' already declared for route '/'` but I didn't have any collisions.

```javascript
import fastifySwaggerUi, { FastifySwaggerUiOptions } from '@fastify/swagger-ui';
import fp from 'fastify-plugin';

export default fp<FastifySwaggerUiOptions>(
    async (fastify, opts) => { // here we still get opts = {prefix: '/'} because AutoLoad adds it, as the object seems empty
        await fastify.register(fastifySwaggerUi, opts);
    }
);

export const autoConfig: FastifySwaggerUiOptions = {
    prefix: undefined,
};
```

### Example

_No response_

### PR DESCRIPTION
**Pull request by inyourtime**
fixes #223 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/main/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

File: index.js [hunk 1]
```diff
@@ -10,19 +10,19 @@ async function fastifySwaggerUi (fastify, opts) {
 
   // if no logo is provided, read default static logo
   let logoContent = opts.logo
-  if (logoContent == null) {
+  if (logoContent === undefined) {
```
Comment (Eomm) [inline index.js:13]: the `== null` was catching both null and undefined. Why this change?

Comment (inyourtime) [reply index.js:13]: With this test:
https://github.com/fastify/fastify-swagger-ui/blob/3e01bb5279161b99b15e53034a114b410b61ab13/test/swagger-initializer.test.js#L129-L143

It is possible to avoid using the default logo by setting the logo option to null. The default logo is used only when no logo option is provided.

Comment (inyourtime) [reply index.js:13]: It looks like this was working before because spreading the option object overrides the existing logo key with the value `null`

**Review by Eomm — APPROVED** [review]
